---
- hosts: do
  remote_user: "{{ user }}"

  vars:
    packages:
      - nginx
      - docker
      - git
      - ruby

  tasks:
    - name: install packages
      apt:
        state: installed
        pkg: "{{ item }}"
      with_items: packages
