---
- hosts: localhost
  connection: local

  tasks:
    - name: Create new Droplet
      digital_ocean:
        state: active
        #state: deleted
        command: droplet
        name: ansible-test
        private_networking: no
        size_id: 512mb
        ## coreos
        # image_id: 15607947
        ## ubuntu-15-10-x64
        image_id: 15621816
        region_id: sfo1
        ssh_key_ids: 1694862
        unique_name: yes
      register: do1

    - name: Debug
      debug:
        var: do1

    - name: add new droplet to ansible hosts
      add_host:
        name: "{{ do1.droplet.ip_address }}"
        groups: do1
      when: do1.droplet is defined

    - name: Wait for port 22 to become available
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

    - name: Add admin group
      group:
        name: admin
        state: present

    - name: Add user to server
      user:
        name: frob
        group: admin
        createhome: yes
